import { StyledComponentsRegistry } from './registry';
import Header from '../components/Header';
import './global.css';
import { Metadata } from 'next';
import { Container } from '@mui/material';

export const metadata: Metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Header />
          <Container component="main">{children}</Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
